#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

echo "Fixing permission"
#ps aux | egrep '(apache|httpd)'

#HTTPDUSER=$(ps axo user,comm | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1)
#echo $APACHE_RUN_USER
setfacl -dR -m u:www-data:rwX -m u:root:rwX /var/www/html/var
setfacl -R -m u:www-data:rwX -m u:root:rwX /var/www/html/var

exec "$@"